<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="isubrama" name="com.training.sanity.tests.ReturnOrder" tests="5" failures="0" timestamp="28 Aug 2019 09:26:06 GMT" time="5.318" errors="1">
  <testcase name="setUpBeforeClass" time="5.318" classname="com.training.sanity.tests.ReturnOrder">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.relevantcodes.extentreports.Report.loadConfig(Report.java:480)
at com.relevantcodes.extentreports.ExtentReports.loadConfig(ExtentReports.java:481)
at com.training.sanity.tests.LoginTests.setUpBeforeClass(LoginTests.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUpBeforeClass -->
  <testcase name="validLoginTest" time="0.000" classname="com.training.sanity.tests.ReturnOrder">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase name="validateFilterOrder" time="0.000" classname="com.training.sanity.tests.ReturnOrder">
    <skipped/>
  </testcase> <!-- validateFilterOrder -->
  <testcase name="validateDeleteOrder" time="0.000" classname="com.training.sanity.tests.ReturnOrder">
    <skipped/>
  </testcase> <!-- validateDeleteOrder -->
  <testcase name="validateReturnOrder" time="0.000" classname="com.training.sanity.tests.ReturnOrder">
    <skipped/>
  </testcase> <!-- validateReturnOrder -->
</testsuite> <!-- com.training.sanity.tests.ReturnOrder -->
